stevebauman/showcode

components/Preview.vue, components/Window.vue
Not sure if the options should be percentages rather than pixel values. I went with pixel values to maintain consistency with the font size.
=> [Feature] Add option to change line height

components/Preview.vue, components/Window.vue
=> Add ability to disable shadow

components/Preview.vue, components/Window.vue
Closes https://github.com/stevebauman/showcode/issues/13
=> Add ability to disable entire header

components/Preview.vue
=> Add conic backgrounds

components/Page.vue, package-lock.json, package.json, pages/index.vue
Closes https://github.com/stevebauman/showcode/issues/47
=> Add ability to import and export configuration files

components/ButtonResize.vue, components/ControlRow.vue, components/ControlSection.vue, components/Preview.vue
=> Remove width and height restrictions and add background padding slider

components/ButtonBackground.vue, components/ButtonResize.vue, components/Dropdown.vue, components/Editor.vue, components/FileDropdown.vue, components/Modal.vue, components/Preview.vue, components/Range.vue, components/Tab.vue, components/Toggle.vue, components/ToolbarButton.vue, pages/index.vue, tailwind.config.js
Makes it easy to change the focus color later if needed. :)
=> Added `ui-focus` color.

components/Editor.vue, components/Preview.vue
https://github.com/stevebauman/showcode/issues/69
=> Debounce code token generation

components/ButtonBackground.vue, components/Preview.vue, components/Window.vue
=> Add ability to remove faux menu

components/Dropdown.vue, components/Preview.vue
=> Increase z-index of export dropdown

components/Alert.vue, components/Preview.vue, pages/index.vue, plugins/vue-tailwind.js
=> Add Firefox clipboard unsupported message

components/Preview.vue, components/Tab.vue, components/Window.vue, pages/index.vue
=> Use project title as export file name

components/Editor.vue
See https://twitter.com/SteveTheBauman/status/1478050720129683460
=> Remove blue cursor outline in Monaco

components/Button.vue, components/ButtonResize.vue, components/ModalBackground.vue, components/Preview.vue, components/Window.vue, nuxt.config.js, package-lock.json, package.json, pages/index.vue, tailwind.config.js
Closes https://github.com/stevebauman/showcode/issues/93
=> Implement aspect ratios, composition API, and hidden scrollbars

components/Code.vue, components/Label.vue, components/Page.vue, components/Preview.vue, components/Window.vue, composables/usePreview.js
Closes https://github.com/stevebauman/showcode/issues/81
=> Feature code orientation

components/Editor.vue, components/Page.vue, components/Preview.vue
Closes https://github.com/stevebauman/showcode/issues/50
=> Feature flip code preview

assets/css/main.css, components/Input.vue, components/Preview.vue, composables/usePreview.js
https://twitter.com/jorqensen/status/1515597339402149891
=> Add dimension inputs

assets/css/main.css, assets/css/prism-dark.css, assets/loading.html, components/Modal.vue, components/Monaco.vue, components/ToggleDarkMode.vue, composables/useApplicationStore.js, composables/useSettingsStore.js, pages/index.vue
Closes #134 
@lupinitylabs Could you give this a test on your end when the PR Netlify instance has finished deploying?
=> Use global application store to manage dark mode

components/Preview.vue, components/Window.vue
=> Fix - "Fit to Window" doesn't take "Scale" into account

components/Preview.vue
=> Resize canvas when "Fit to Window" is locked and header or title is toggled

components/ModalPreferences.vue, components/Monaco.vue, composables/usePreferencesStore.js
Closes https://github.com/stevebauman/showcode/issues/144
=> Add editor font size preference

components/Preview.vue, components/ToggleShadow.vue, components/Window.vue, composables/usePreview.js
=> Add ability to configure border radius

components/Code.vue, components/CodeLine.vue, components/FormDivider.vue, components/ModalPreferences.vue, components/Monaco.vue, components/Preview.vue, composables/usePreferencesStore.js
=> Add ability to change focused code blur strength

components/ButtonTheme.vue, components/Editor.vue, components/Monaco.vue, components/Popover.vue, components/PopoverSettings.vue, components/Preview.vue, content/changelog.md, data/emojis.json, package-lock.json, package.json
=> Add emoji picker

components/Tab.vue, components/TabButton.vue, composables/useProjectStoreFactory.js, composables/useProjectStores.js, content/changelog.md, pages/index.vue
=> Add ability to duplicate tabs

data/backgrounds.js
Backgrounds added from https://codioful.com/.
=> Add Codioful backgrounds

components/Canvas.vue, components/Preview.vue
=> Fix fit to window
